### ISSUE TITLE
My second monitor doesn't work.

### ISSUE THREAD

**Issue by RUNFUNRUN** [JaKooLit/Hyprland-v2.2#1]
I edited `.config/hypr/configs/monitors.conf` , but It doesn't work.
If you know anything about this please let me know.

But the login screen is output on my second monitor.

```
monitor=DP-2,1980x1080@240,0x0,1
workspace=DP-2,1
monitor=DP-3,2560x1440@165,1980x0,1,transform,3
workspace=DP-3,2
```

```
$ hyprctl monitors
Monitor DP-2 (ID 0):
	1920x1080@60.000000 at 0x0
	description: Dell Inc. DELL S2522HG 685K1C3 (DP-2)
	make: Dell Inc.
	model: DELL S2522HG
	serial: 685K1C3
	active workspace: 1 (1)
	reserved: 0 42 0 0
	scale: 1.00
	transform: 0
	focused: yes
	dpmsStatus: 1
	vrr: 0

Monitor DP-3 (ID 1):
	2560x1440@164.802002 at 1980x0
	description: Huawei Technologies Co., Inc. XWU-CBA 0x00000001 (DP-3)
	make: Huawei Technologies Co., Inc.
	model: XWU-CBA
	serial: 0x00000001
	active workspace: 2 (2)
	reserved: 0 42 0 0
	scale: 1.00
	transform: 3
	focused: no
	dpmsStatus: 1
	vrr: 0
```

**Comment by RUNFUNRUN** [comment]
![20230529_104552.jpg](https://github.com/JaKooLit/Hyprland-v2.2/assets/90281553/ae50b42b-f989-4bff-af7f-bec0a99bfa0c)

![20230529_104608.jpg](https://github.com/JaKooLit/Hyprland-v2.2/assets/90281553/88c10abd-79b4-4ed8-8c39-1996a81ba068)

**Comment by JaKooLit** [comment]
hmmm transform 3 is 270 degrees. I would imagine that you want your huwaei monitor to rotate vertical. Have you tried changing transform to 2 instead?

https://wiki.hyprland.org/Configuring/Monitors/#rotating

and as per hyprctl monitor, your dell monitor is only 60hz. You set at 240hz

**Comment by RUNFUNRUN** [comment]
Certainly, looking at the output of the command, it was 60Hz.  I will try it when I get home.  thank you!

**Comment by RUNFUNRUN** [comment]
It works!
And it switched to 3 from 2, It works too.
Your script is awesome for beginners like me:)
Thank you!
